const tailwindcss = require("tailwindcss");
const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  mode: "jit",
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      xs: "480px",
      ...defaultTheme.screens,
    },
    extend: {
      inset: {
        17: "68px",
        26: "104px",
      },
      backgroundImage: {
        bt: "url('../../assets/images/biotech-bkg 1.png')",
        admission: "url('../../assets/images/admission-bkg.jpg')",
        ai_ml: "url('../../assets/images/ai.jpg')",
        ai_ds: "url('../../assets/images/.jpg')",
        arch: "url('../../assets/images/archi.jpg')",
        chem: "url('../../assets/images/chemical.jpg')",
        chy: "url('../../assets/images/chemistry.jpg')",
        cs: "url('../../assets/images/admission-bkg.jpg')",
        cv: "url('../../assets/images/admission-bkg.jpg')",
        cs_ai: "url('../../assets/images/ai.jpg')",
        cs_cs: "url('../../assets/images/admission-bkg.jpg')",
        eee: "url('../../assets/images/biotech-bkg 1.png')",
        ece: "url('../../assets/images/admission-bkg.jpg')",
        ete: "url('../../assets/images/biotech-bkg 1.png')",
        eie: "url('../../assets/images/admission-bkg.jpg')",
        hss: "url('../../assets/images/biotech-bkg 1.png')",
        iem: "url('../../assets/images/admission-bkg.jpg')",
        ise: "url('../../assets/images/biotech-bkg 1.png')",
        mat: "url('../../assets/images/biotech-bkg 1.png')",
        mech: "url('../../assets/images/admission-bkg.jpg')",
        phy: "url('../../assets/images/admission-bkg.jpg')",
        ml: "url('../../assets/images/admission-bkg.jpg')",
        exam: "url('../../assets/images/exam-bkg.jpg')",
        lib: "url('../../assets/images/admission-bkg.jpg')",
        hostel: "url('../../assets/images/admission-bkg.jpg')",
        internet: "url('../../assets/images/admission-bkg.jpg')",
        other_facilities: "url('../../assets/images/admission-bkg.jpg')",
        sports: "url('../../assets/images/admission-bkg.jpg')",
        placement: "url('../../assets/images/admission-bkg.jpg')",
        about: "url('../../assets/images/admission-bkg.jpg')",
        contact: "url('../../assets/images/contact-us.jpg')",
        deca: "url('../../assets/images/admission-bkg.jpg')",
        spdc: "url('../../assets/images/admission-bkg.jpg')",
        edc: "url('../../assets/images/admission-bkg.jpg')",
        nss: "url('../../assets/images/admission-bkg.jpg')",
        proctor: "url('../../assets/images/admission-bkg.jpg')",
        cocurricular: "url('../../assets/images/admission-bkg.jpg')",
        alumni: "url('../../assets/images/admission-bkg.jpg')",
        aatce: "url('../../assets/images/admission-bkg.jpg')",
        teqip: "url('../../assets/images/admission-bkg.jpg')",
        homeBanner: "url('../../assets/images/msrit-campus.jpg')",
        homeBannerJnanam: "url('../../assets/images/image 1.png')",
        samMsr: "url('../../assets/images/sam-msr.png')",
        rightSideHome: "url('../../assets/images/right-side.png')",
        star: "url('../../assets/images/star.png')",
      },
      colors: {
        transparent: "transparent",
        current: "currentColor",
        blue: {
          ramaiah: "#361c6a",
        },
        pink: {
          // ramaiah: "#992361",
          ramaiah: "rgba(157,29,89,1)",
        },
        orange: {
          // ramaiah: "#E34A21",
          ramaiah: "rgba(222,63,15,1)",
        },
        gray: {
          menu: "#C1B3B0",
          deptHeader: "#E2E2E2",
          homeSection: "#DDDDDD",
          homeBannerGray: "rgba(243, 244, 246, .8)",
        },
      },
      fontFamily: {
        body: "Gotham Book",
        heading: "Gotham Bold",
        lightBody: "Gotham Book",
        quoto: "Gotham Book Italic",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require("daisyui")],
};
